### ISSUE TITLE
Clang UBSAN runtime warnings: UndefinedBehaviorSanitizer: invalid-shift-base (linux-x86_64)

### ISSUE THREAD

**Issue by patricksnape** [explosion/cython-blis#58]
When trying to build blis with my local compiler setup (linux-x86_64 target) - clang complains about 

```
SUMMARY: UndefinedBehaviorSanitizer: blis.h

blis.h runtime error: left shift of 7 by 29 places cannot be represented in type 'int'
    #0 0x7ffb69e87899 in bli_obj_set_comp_dt blis/_src/include/linux-x86_64/blis.h
    #1 0x7ffb69e86f54 in bli_obj_create_without_buffer blis/_src/frame/base/bli_obj.c
    #2 0x7ffb69e87cbe in bli_obj_create_1x1_with_attached_buffer blis/_src/frame/base/bli_obj.c
    #3 0x7ffb69e79ea7 in bli_sgemm_ex blis/_src/frame/3/bli_l3_tapi.c
```

[Looking at the code](https://raw.githubusercontent.com/explosion/cython-blis/master/blis/_src/include/linux-x86_64/blis.h) the offending section seems to be:

```
static void bli_obj_set_comp_dt( num_t dt, obj_t* obj )
{
	obj->info = ( objbits_t )
	            ( obj->info & ~BLIS_COMP_DT_BITS ) |
	            ( dt << BLIS_COMP_DT_SHIFT );
}
```

but I think the actual issues are the defines around things like `BLIS_COMP_DT_BITS` which is

```
#define BLIS_COMP_DT_BITS                  ( 0x7  << BLIS_COMP_DT_SHIFT )
```

e.g. a left shift of 29 to the constant 7 -> which invokes undefined behavior according to clang. What is the intention of this code? To create a big signed wrap around value e.g -536870912?

**Comment by patricksnape** [comment]
That’s a very good point. Sorry I totally blanked that this was just a wrapper around blis. Thanks for pointing me out the related issue. I ended up adding an attribute to the complaining methods to disable the ubsan.
